[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
# Use the CMD from Dockerfile instead of overriding it
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[var]
RAILWAY_ENVIRONMENT = "true" 