[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
# Use the CMD from Dockerfile instead of overriding it
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[var]
RAILWAY_ENVIRONMENT = "true"
# IMPORTANT: DO NOT add sensitive variables here!
# Add these variables through the Railway dashboard:
# https://railway.app/dashboard > Your Project > Variables
#
# Required variables:
# - OPENAI_API_KEY
# - SUPABASE_URL
# - SUPABASE_KEY
# - DATABASE_URL 